TK_1_PPW/urls.py
from django.contrib import admin
from django.urls import path, include

# static files
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls'), name='main'),
    path('approval-list/',include('approvalList.urls')),
    path('start-sell/',include('startsell.urls'), name="startSell"),
    path('save-item/',include('sellItem.urls')),
    path('products/', include('products.urls'), name='products'),
    path('product-detail/', include('detailBarang.urls')),
    path('item-list/',include('itemList.urls')),
    path('signup/', include('otentikasi.urls')),
    path('sellerLogin/', include('sellerLogin.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = 'loginShopper/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'homepage/index.html'), name='logout'),
]

urlpatterns += staticfiles_urlpatterns()
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

sellItem/urls.py
from django.urls import path
from .views import saveItem

app_name = 'sellItem'

urlpatterns= [
	path('', saveItem, name = 'saveItem')
]

sellItem/models.py
from django.db import models

# Create your models here.
from decimal import Decimal

class Category(models.Model):
    name = models.TextField()
    price = models.DecimalField(max_digits=9, decimal_places=3, default=Decimal('0.0000'))

    DRESS = 'Dress'
    T_SHIRT = 'T-Shirt'
    SKIRT = 'Skirt'
    JUMPSUIT = 'Jumpsuit'
    PANTS_LEGGINGS = 'Pants & Leggings'
    JEANS = 'Jeans'
    SWIMWEAR = 'Swimwear'
    KNITWEAR_CARDIGANS = 'Knitwear & Cardigans'
    HOODIES_SWEATSHIRTS = 'Hoodies & Sweatshirts'
    BLAZER = 'Blazer'
    JACKET_COATS = 'Jacket & Coats'
    SLEEPWEAR = 'Sleepwear'
    ACCESSORIES = 'Accessories'
    ALL = 'All'

    CATEGORY_CHOICES = [
    (ALL, 'All'), (DRESS, 'Dress'), (T_SHIRT, 'T-Shirt'),
    (SKIRT, 'Skirt'), (JUMPSUIT, 'Jumpsuit'),
    (PANTS_LEGGINGS, 'Pants & Leggings'),
    (JEANS, 'Jeans'), (SWIMWEAR, 'Swimwear'),
    (KNITWEAR_CARDIGANS, 'Knitwear & Cardigans'),
    (HOODIES_SWEATSHIRTS, 'Hoodies & Sweatshirts'),
    (BLAZER, 'Blazer'), (JACKET_COATS, 'Jacket & Coats'),
    (SLEEPWEAR, 'Sleepwear'), (ACCESSORIES, 'Accessories')
    ]

    category = models.CharField(max_length = 100,
        choices=CATEGORY_CHOICES, default = ALL,
        )

    description = models.TextField()
    image = models.ImageField(upload_to = 'images/', default = 'images/hnm.jpg')

    def __str__(self):
        return self.name + ":" + str(self.image)

sellItem/views.py
from django.shortcuts import render,redirect
from .form import addItem
from .models import Category

# Create your views here.
def saveItem(request):
	if request.method == 'POST':
		form = addItem(request.POST, request.FILES)
		if form.is_valid():
			Category.objects.create(**form.cleaned_data)
		form = addItem()
		categorys = Category.objects.all()
		context ={
			'form' : form,
			'category' : categorys
		}

		return render(request, 'sellItem/sellitem.html', context)
	else:
		form = addItem()
		categorys = Category.objects.all()
		context ={
			'form' : form,
			'category' : categorys
		}
	return render(request, 'sellItem/sellitem.html', context )

sellItem/templates/sellItem/sellitem.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>AppaRental</title>
</head>

<body>
    
    <div class="top-footer">
        <a href="{% url 'homepage' %}">
            <button type="button" class="logo" style="font-family: Asap;
            font-style: normal;
            font-weight: bold;
            font-size: 24px;
            line-height: 30px;
        
            color: #252C29;
            padding: 0.2rem 0.5rem;
            background-color: #FFFFFF;
            border: 3px solid #252C29;
            margin-bottom: 1rem;
            margin-left: 2.3rem;
            margin-top: 2.5rem;">AppaRental.</button>
        </a>
    </div>

    <div class="container-fluid" id="wrapper-top">
        <a class="tulisan-back" href="/start-sell">
            <i class="fa fa-arrow-circle-left"></i>
            <p style="font-family: Open Sans;
            font-style: normal;
            font-weight: 600;
            font-size: 14px;
            line-height: 19px;
            /* identical to box height */
        
            color: #252C29;">Back to Seller Page</p>
        </a>

        <div class="container-fluid" id="wrapper">
                
                <div class="bawah">
                    <div class="apa-coba">
                        <h5>Sell Your Item</h5>
                        <hr>
                    </div>

                    <div class="container-fluid" id="wrapper_content">
                       <form method = "POST" enctype="multipart/form-data" action="{%url 'sellItem:saveItem' %}">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class='bawah'>
                            <input type="submit" class="submit" value="Sell Item">
                        </div>
                    </div>

                </div>
        </div>
    </div>

    <div class="bottom-footer" style="margin-bottom: 2.4rem;
        margin-left: 2.3rem;
        margin-top: 2.5rem;">
        <p style="font-family: Open Sans;
        font-style: normal;
        font-weight: 600;
        font-size: 18px;
        line-height: 25px;

        color: #252C29;">© 2019 All rights served</p>
    </div>

    <!-- Optional JavaScript -->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'js/jquery.easing.min.js' %}"></script>

    <!-- Custom JavaScript for this theme -->
    <script src="{% static 'js/scrolling-nav.js' %}"></script>

</body>

</html>